site_name: Unraveling Frappe
theme:
  name: material
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  plugins:
    - glightbox
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/omar25muhammad
    - icon: fontawesome/brands/linkedin
      link: https://ly.linkedin.com/in/omar-m-k-shehada
    - icon: fontawesome/brands/telegram
      link: https://t.me/omar25muhammed
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/218923947475

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://github.com/omar25muhammad"  target="_blank" rel="noopener">Omar M. K. Shehada</a>
